### ISSUE TITLE
"Uncaught ReferenceError: show is not defined" on game startup

### ISSUE THREAD

**Issue by James103** [Reinhardt-C/Ripoff-Idle#20]
Attempting to start the game yields the following error. Refreshing and/or wiping the save does not help (I tested it).
```
Uncaught ReferenceError: show is not defined
    at showElems (showelem.js:35)
    at gameLoop (main.js:69)
```

**Comment by Reinhardt-C** [comment]
I don't really code this game anymore, I focus on True Infinity. I might look into it at some point.

**Comment by e666666** [comment]
Fixed!

**Comment by James103** [comment]
Thanks!
